// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: plugin.proto

package libplugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SshPiperPlugin_Logs_FullMethodName                      = "/libplugin.SshPiperPlugin/Logs"
	SshPiperPlugin_ListCallbacks_FullMethodName             = "/libplugin.SshPiperPlugin/ListCallbacks"
	SshPiperPlugin_NewConnection_FullMethodName             = "/libplugin.SshPiperPlugin/NewConnection"
	SshPiperPlugin_NextAuthMethods_FullMethodName           = "/libplugin.SshPiperPlugin/NextAuthMethods"
	SshPiperPlugin_NoneAuth_FullMethodName                  = "/libplugin.SshPiperPlugin/NoneAuth"
	SshPiperPlugin_PasswordAuth_FullMethodName              = "/libplugin.SshPiperPlugin/PasswordAuth"
	SshPiperPlugin_PublicKeyAuth_FullMethodName             = "/libplugin.SshPiperPlugin/PublicKeyAuth"
	SshPiperPlugin_KeyboardInteractiveAuth_FullMethodName   = "/libplugin.SshPiperPlugin/KeyboardInteractiveAuth"
	SshPiperPlugin_UpstreamAuthFailureNotice_FullMethodName = "/libplugin.SshPiperPlugin/UpstreamAuthFailureNotice"
	SshPiperPlugin_Banner_FullMethodName                    = "/libplugin.SshPiperPlugin/Banner"
	SshPiperPlugin_VerifyHostKey_FullMethodName             = "/libplugin.SshPiperPlugin/VerifyHostKey"
	SshPiperPlugin_PipeCreateErrorNotice_FullMethodName     = "/libplugin.SshPiperPlugin/PipeCreateErrorNotice"
	SshPiperPlugin_PipeStartNotice_FullMethodName           = "/libplugin.SshPiperPlugin/PipeStartNotice"
	SshPiperPlugin_PipeErrorNotice_FullMethodName           = "/libplugin.SshPiperPlugin/PipeErrorNotice"
)

// SshPiperPluginClient is the client API for SshPiperPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SshPiperPluginClient interface {
	Logs(ctx context.Context, in *StartLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error)
	ListCallbacks(ctx context.Context, in *ListCallbackRequest, opts ...grpc.CallOption) (*ListCallbackResponse, error)
	NewConnection(ctx context.Context, in *NewConnectionRequest, opts ...grpc.CallOption) (*NewConnectionResponse, error)
	NextAuthMethods(ctx context.Context, in *NextAuthMethodsRequest, opts ...grpc.CallOption) (*NextAuthMethodsResponse, error)
	NoneAuth(ctx context.Context, in *NoneAuthRequest, opts ...grpc.CallOption) (*NoneAuthResponse, error)
	PasswordAuth(ctx context.Context, in *PasswordAuthRequest, opts ...grpc.CallOption) (*PasswordAuthResponse, error)
	PublicKeyAuth(ctx context.Context, in *PublicKeyAuthRequest, opts ...grpc.CallOption) (*PublicKeyAuthResponse, error)
	KeyboardInteractiveAuth(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage], error)
	UpstreamAuthFailureNotice(ctx context.Context, in *UpstreamAuthFailureNoticeRequest, opts ...grpc.CallOption) (*UpstreamAuthFailureNoticeResponse, error)
	Banner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*BannerResponse, error)
	VerifyHostKey(ctx context.Context, in *VerifyHostKeyRequest, opts ...grpc.CallOption) (*VerifyHostKeyResponse, error)
	PipeCreateErrorNotice(ctx context.Context, in *PipeCreateErrorNoticeRequest, opts ...grpc.CallOption) (*PipeCreateErrorNoticeResponse, error)
	PipeStartNotice(ctx context.Context, in *PipeStartNoticeRequest, opts ...grpc.CallOption) (*PipeStartNoticeResponse, error)
	PipeErrorNotice(ctx context.Context, in *PipeErrorNoticeRequest, opts ...grpc.CallOption) (*PipeErrorNoticeResponse, error)
}

type sshPiperPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewSshPiperPluginClient(cc grpc.ClientConnInterface) SshPiperPluginClient {
	return &sshPiperPluginClient{cc}
}

func (c *sshPiperPluginClient) Logs(ctx context.Context, in *StartLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SshPiperPlugin_ServiceDesc.Streams[0], SshPiperPlugin_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartLogRequest, Log]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SshPiperPlugin_LogsClient = grpc.ServerStreamingClient[Log]

func (c *sshPiperPluginClient) ListCallbacks(ctx context.Context, in *ListCallbackRequest, opts ...grpc.CallOption) (*ListCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCallbackResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_ListCallbacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) NewConnection(ctx context.Context, in *NewConnectionRequest, opts ...grpc.CallOption) (*NewConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewConnectionResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_NewConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) NextAuthMethods(ctx context.Context, in *NextAuthMethodsRequest, opts ...grpc.CallOption) (*NextAuthMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextAuthMethodsResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_NextAuthMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) NoneAuth(ctx context.Context, in *NoneAuthRequest, opts ...grpc.CallOption) (*NoneAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoneAuthResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_NoneAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) PasswordAuth(ctx context.Context, in *PasswordAuthRequest, opts ...grpc.CallOption) (*PasswordAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordAuthResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_PasswordAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) PublicKeyAuth(ctx context.Context, in *PublicKeyAuthRequest, opts ...grpc.CallOption) (*PublicKeyAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicKeyAuthResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_PublicKeyAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) KeyboardInteractiveAuth(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SshPiperPlugin_ServiceDesc.Streams[1], SshPiperPlugin_KeyboardInteractiveAuth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SshPiperPlugin_KeyboardInteractiveAuthClient = grpc.BidiStreamingClient[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage]

func (c *sshPiperPluginClient) UpstreamAuthFailureNotice(ctx context.Context, in *UpstreamAuthFailureNoticeRequest, opts ...grpc.CallOption) (*UpstreamAuthFailureNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpstreamAuthFailureNoticeResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_UpstreamAuthFailureNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) Banner(ctx context.Context, in *BannerRequest, opts ...grpc.CallOption) (*BannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BannerResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_Banner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) VerifyHostKey(ctx context.Context, in *VerifyHostKeyRequest, opts ...grpc.CallOption) (*VerifyHostKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyHostKeyResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_VerifyHostKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) PipeCreateErrorNotice(ctx context.Context, in *PipeCreateErrorNoticeRequest, opts ...grpc.CallOption) (*PipeCreateErrorNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipeCreateErrorNoticeResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_PipeCreateErrorNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) PipeStartNotice(ctx context.Context, in *PipeStartNoticeRequest, opts ...grpc.CallOption) (*PipeStartNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipeStartNoticeResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_PipeStartNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperPluginClient) PipeErrorNotice(ctx context.Context, in *PipeErrorNoticeRequest, opts ...grpc.CallOption) (*PipeErrorNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PipeErrorNoticeResponse)
	err := c.cc.Invoke(ctx, SshPiperPlugin_PipeErrorNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SshPiperPluginServer is the server API for SshPiperPlugin service.
// All implementations must embed UnimplementedSshPiperPluginServer
// for forward compatibility.
type SshPiperPluginServer interface {
	Logs(*StartLogRequest, grpc.ServerStreamingServer[Log]) error
	ListCallbacks(context.Context, *ListCallbackRequest) (*ListCallbackResponse, error)
	NewConnection(context.Context, *NewConnectionRequest) (*NewConnectionResponse, error)
	NextAuthMethods(context.Context, *NextAuthMethodsRequest) (*NextAuthMethodsResponse, error)
	NoneAuth(context.Context, *NoneAuthRequest) (*NoneAuthResponse, error)
	PasswordAuth(context.Context, *PasswordAuthRequest) (*PasswordAuthResponse, error)
	PublicKeyAuth(context.Context, *PublicKeyAuthRequest) (*PublicKeyAuthResponse, error)
	KeyboardInteractiveAuth(grpc.BidiStreamingServer[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage]) error
	UpstreamAuthFailureNotice(context.Context, *UpstreamAuthFailureNoticeRequest) (*UpstreamAuthFailureNoticeResponse, error)
	Banner(context.Context, *BannerRequest) (*BannerResponse, error)
	VerifyHostKey(context.Context, *VerifyHostKeyRequest) (*VerifyHostKeyResponse, error)
	PipeCreateErrorNotice(context.Context, *PipeCreateErrorNoticeRequest) (*PipeCreateErrorNoticeResponse, error)
	PipeStartNotice(context.Context, *PipeStartNoticeRequest) (*PipeStartNoticeResponse, error)
	PipeErrorNotice(context.Context, *PipeErrorNoticeRequest) (*PipeErrorNoticeResponse, error)
	mustEmbedUnimplementedSshPiperPluginServer()
}

// UnimplementedSshPiperPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSshPiperPluginServer struct{}

func (UnimplementedSshPiperPluginServer) Logs(*StartLogRequest, grpc.ServerStreamingServer[Log]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedSshPiperPluginServer) ListCallbacks(context.Context, *ListCallbackRequest) (*ListCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCallbacks not implemented")
}
func (UnimplementedSshPiperPluginServer) NewConnection(context.Context, *NewConnectionRequest) (*NewConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewConnection not implemented")
}
func (UnimplementedSshPiperPluginServer) NextAuthMethods(context.Context, *NextAuthMethodsRequest) (*NextAuthMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NextAuthMethods not implemented")
}
func (UnimplementedSshPiperPluginServer) NoneAuth(context.Context, *NoneAuthRequest) (*NoneAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NoneAuth not implemented")
}
func (UnimplementedSshPiperPluginServer) PasswordAuth(context.Context, *PasswordAuthRequest) (*PasswordAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PasswordAuth not implemented")
}
func (UnimplementedSshPiperPluginServer) PublicKeyAuth(context.Context, *PublicKeyAuthRequest) (*PublicKeyAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicKeyAuth not implemented")
}
func (UnimplementedSshPiperPluginServer) KeyboardInteractiveAuth(grpc.BidiStreamingServer[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage]) error {
	return status.Error(codes.Unimplemented, "method KeyboardInteractiveAuth not implemented")
}
func (UnimplementedSshPiperPluginServer) UpstreamAuthFailureNotice(context.Context, *UpstreamAuthFailureNoticeRequest) (*UpstreamAuthFailureNoticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpstreamAuthFailureNotice not implemented")
}
func (UnimplementedSshPiperPluginServer) Banner(context.Context, *BannerRequest) (*BannerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Banner not implemented")
}
func (UnimplementedSshPiperPluginServer) VerifyHostKey(context.Context, *VerifyHostKeyRequest) (*VerifyHostKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyHostKey not implemented")
}
func (UnimplementedSshPiperPluginServer) PipeCreateErrorNotice(context.Context, *PipeCreateErrorNoticeRequest) (*PipeCreateErrorNoticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PipeCreateErrorNotice not implemented")
}
func (UnimplementedSshPiperPluginServer) PipeStartNotice(context.Context, *PipeStartNoticeRequest) (*PipeStartNoticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PipeStartNotice not implemented")
}
func (UnimplementedSshPiperPluginServer) PipeErrorNotice(context.Context, *PipeErrorNoticeRequest) (*PipeErrorNoticeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PipeErrorNotice not implemented")
}
func (UnimplementedSshPiperPluginServer) mustEmbedUnimplementedSshPiperPluginServer() {}
func (UnimplementedSshPiperPluginServer) testEmbeddedByValue()                        {}

// UnsafeSshPiperPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SshPiperPluginServer will
// result in compilation errors.
type UnsafeSshPiperPluginServer interface {
	mustEmbedUnimplementedSshPiperPluginServer()
}

func RegisterSshPiperPluginServer(s grpc.ServiceRegistrar, srv SshPiperPluginServer) {
	// If the following call panics, it indicates UnimplementedSshPiperPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SshPiperPlugin_ServiceDesc, srv)
}

func _SshPiperPlugin_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SshPiperPluginServer).Logs(m, &grpc.GenericServerStream[StartLogRequest, Log]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SshPiperPlugin_LogsServer = grpc.ServerStreamingServer[Log]

func _SshPiperPlugin_ListCallbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).ListCallbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_ListCallbacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).ListCallbacks(ctx, req.(*ListCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_NewConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).NewConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_NewConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).NewConnection(ctx, req.(*NewConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_NextAuthMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextAuthMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).NextAuthMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_NextAuthMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).NextAuthMethods(ctx, req.(*NextAuthMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_NoneAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoneAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).NoneAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_NoneAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).NoneAuth(ctx, req.(*NoneAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_PasswordAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).PasswordAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_PasswordAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).PasswordAuth(ctx, req.(*PasswordAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_PublicKeyAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).PublicKeyAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_PublicKeyAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).PublicKeyAuth(ctx, req.(*PublicKeyAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_KeyboardInteractiveAuth_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SshPiperPluginServer).KeyboardInteractiveAuth(&grpc.GenericServerStream[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SshPiperPlugin_KeyboardInteractiveAuthServer = grpc.BidiStreamingServer[KeyboardInteractiveAuthMessage, KeyboardInteractiveAuthMessage]

func _SshPiperPlugin_UpstreamAuthFailureNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpstreamAuthFailureNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).UpstreamAuthFailureNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_UpstreamAuthFailureNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).UpstreamAuthFailureNotice(ctx, req.(*UpstreamAuthFailureNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_Banner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).Banner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_Banner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).Banner(ctx, req.(*BannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_VerifyHostKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyHostKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).VerifyHostKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_VerifyHostKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).VerifyHostKey(ctx, req.(*VerifyHostKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_PipeCreateErrorNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipeCreateErrorNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).PipeCreateErrorNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_PipeCreateErrorNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).PipeCreateErrorNotice(ctx, req.(*PipeCreateErrorNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_PipeStartNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipeStartNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).PipeStartNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_PipeStartNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).PipeStartNotice(ctx, req.(*PipeStartNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperPlugin_PipeErrorNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipeErrorNoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperPluginServer).PipeErrorNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperPlugin_PipeErrorNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperPluginServer).PipeErrorNotice(ctx, req.(*PipeErrorNoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SshPiperPlugin_ServiceDesc is the grpc.ServiceDesc for SshPiperPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SshPiperPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "libplugin.SshPiperPlugin",
	HandlerType: (*SshPiperPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCallbacks",
			Handler:    _SshPiperPlugin_ListCallbacks_Handler,
		},
		{
			MethodName: "NewConnection",
			Handler:    _SshPiperPlugin_NewConnection_Handler,
		},
		{
			MethodName: "NextAuthMethods",
			Handler:    _SshPiperPlugin_NextAuthMethods_Handler,
		},
		{
			MethodName: "NoneAuth",
			Handler:    _SshPiperPlugin_NoneAuth_Handler,
		},
		{
			MethodName: "PasswordAuth",
			Handler:    _SshPiperPlugin_PasswordAuth_Handler,
		},
		{
			MethodName: "PublicKeyAuth",
			Handler:    _SshPiperPlugin_PublicKeyAuth_Handler,
		},
		{
			MethodName: "UpstreamAuthFailureNotice",
			Handler:    _SshPiperPlugin_UpstreamAuthFailureNotice_Handler,
		},
		{
			MethodName: "Banner",
			Handler:    _SshPiperPlugin_Banner_Handler,
		},
		{
			MethodName: "VerifyHostKey",
			Handler:    _SshPiperPlugin_VerifyHostKey_Handler,
		},
		{
			MethodName: "PipeCreateErrorNotice",
			Handler:    _SshPiperPlugin_PipeCreateErrorNotice_Handler,
		},
		{
			MethodName: "PipeStartNotice",
			Handler:    _SshPiperPlugin_PipeStartNotice_Handler,
		},
		{
			MethodName: "PipeErrorNotice",
			Handler:    _SshPiperPlugin_PipeErrorNotice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _SshPiperPlugin_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "KeyboardInteractiveAuth",
			Handler:       _SshPiperPlugin_KeyboardInteractiveAuth_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
