// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: plugin.proto

package libplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMethod int32

const (
	AuthMethod_NONE                 AuthMethod = 0
	AuthMethod_PASSWORD             AuthMethod = 1
	AuthMethod_PUBLICKEY            AuthMethod = 2
	AuthMethod_KEYBOARD_INTERACTIVE AuthMethod = 3
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "NONE",
		1: "PASSWORD",
		2: "PUBLICKEY",
		3: "KEYBOARD_INTERACTIVE",
	}
	AuthMethod_value = map[string]int32{
		"NONE":                 0,
		"PASSWORD":             1,
		"PUBLICKEY":            2,
		"KEYBOARD_INTERACTIVE": 3,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type ConnMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FromAddr      string                 `protobuf:"bytes,2,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	UniqId        string                 `protobuf:"bytes,3,opt,name=uniq_id,json=uniqId,proto3" json:"uniq_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnMeta) Reset() {
	*x = ConnMeta{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMeta) ProtoMessage() {}

func (x *ConnMeta) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMeta.ProtoReflect.Descriptor instead.
func (*ConnMeta) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ConnMeta) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ConnMeta) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *ConnMeta) GetUniqId() string {
	if x != nil {
		return x.UniqId
	}
	return ""
}

func (x *ConnMeta) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Upstream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated fields use uri instead.
	//
	// Deprecated: Marked as deprecated in plugin.proto.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Deprecated fields use uri instead.
	//
	// Deprecated: Marked as deprecated in plugin.proto.
	Port          int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	UserName      string `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IgnoreHostKey bool   `protobuf:"varint,4,opt,name=ignore_host_key,json=ignoreHostKey,proto3" json:"ignore_host_key,omitempty"`
	Uri           string `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	// Types that are valid to be assigned to Auth:
	//
	//	*Upstream_None
	//	*Upstream_Password
	//	*Upstream_PrivateKey
	//	*Upstream_RemoteSigner
	//	*Upstream_NextPlugin
	//	*Upstream_RetryCurrentPlugin
	Auth          isUpstream_Auth `protobuf_oneof:"auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in plugin.proto.
func (x *Upstream) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

// Deprecated: Marked as deprecated in plugin.proto.
func (x *Upstream) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Upstream) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Upstream) GetIgnoreHostKey() bool {
	if x != nil {
		return x.IgnoreHostKey
	}
	return false
}

func (x *Upstream) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Upstream) GetAuth() isUpstream_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Upstream) GetNone() *UpstreamNoneAuth {
	if x != nil {
		if x, ok := x.Auth.(*Upstream_None); ok {
			return x.None
		}
	}
	return nil
}

func (x *Upstream) GetPassword() *UpstreamPasswordAuth {
	if x != nil {
		if x, ok := x.Auth.(*Upstream_Password); ok {
			return x.Password
		}
	}
	return nil
}

func (x *Upstream) GetPrivateKey() *UpstreamPrivateKeyAuth {
	if x != nil {
		if x, ok := x.Auth.(*Upstream_PrivateKey); ok {
			return x.PrivateKey
		}
	}
	return nil
}

func (x *Upstream) GetRemoteSigner() *UpstreamRemoteSignerAuth {
	if x != nil {
		if x, ok := x.Auth.(*Upstream_RemoteSigner); ok {
			return x.RemoteSigner
		}
	}
	return nil
}

func (x *Upstream) GetNextPlugin() *UpstreamNextPluginAuth {
	if x != nil {
		if x, ok := x.Auth.(*Upstream_NextPlugin); ok {
			return x.NextPlugin
		}
	}
	return nil
}

func (x *Upstream) GetRetryCurrentPlugin() *UpstreamRetryCurrentPluginAuth {
	if x != nil {
		if x, ok := x.Auth.(*Upstream_RetryCurrentPlugin); ok {
			return x.RetryCurrentPlugin
		}
	}
	return nil
}

type isUpstream_Auth interface {
	isUpstream_Auth()
}

type Upstream_None struct {
	None *UpstreamNoneAuth `protobuf:"bytes,100,opt,name=none,proto3,oneof"`
}

type Upstream_Password struct {
	Password *UpstreamPasswordAuth `protobuf:"bytes,101,opt,name=password,proto3,oneof"`
}

type Upstream_PrivateKey struct {
	PrivateKey *UpstreamPrivateKeyAuth `protobuf:"bytes,102,opt,name=private_key,json=privateKey,proto3,oneof"`
}

type Upstream_RemoteSigner struct {
	RemoteSigner *UpstreamRemoteSignerAuth `protobuf:"bytes,103,opt,name=remote_signer,json=remoteSigner,proto3,oneof"`
}

type Upstream_NextPlugin struct {
	NextPlugin *UpstreamNextPluginAuth `protobuf:"bytes,200,opt,name=next_plugin,json=nextPlugin,proto3,oneof"`
}

type Upstream_RetryCurrentPlugin struct {
	RetryCurrentPlugin *UpstreamRetryCurrentPluginAuth `protobuf:"bytes,201,opt,name=retry_current_plugin,json=retryCurrentPlugin,proto3,oneof"`
}

func (*Upstream_None) isUpstream_Auth() {}

func (*Upstream_Password) isUpstream_Auth() {}

func (*Upstream_PrivateKey) isUpstream_Auth() {}

func (*Upstream_RemoteSigner) isUpstream_Auth() {}

func (*Upstream_NextPlugin) isUpstream_Auth() {}

func (*Upstream_RetryCurrentPlugin) isUpstream_Auth() {}

type UpstreamNoneAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamNoneAuth) Reset() {
	*x = UpstreamNoneAuth{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamNoneAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamNoneAuth) ProtoMessage() {}

func (x *UpstreamNoneAuth) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamNoneAuth.ProtoReflect.Descriptor instead.
func (*UpstreamNoneAuth) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

type UpstreamPasswordAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamPasswordAuth) Reset() {
	*x = UpstreamPasswordAuth{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamPasswordAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamPasswordAuth) ProtoMessage() {}

func (x *UpstreamPasswordAuth) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamPasswordAuth.ProtoReflect.Descriptor instead.
func (*UpstreamPasswordAuth) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *UpstreamPasswordAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpstreamPrivateKeyAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    []byte                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	CaPublicKey   []byte                 `protobuf:"bytes,2,opt,name=ca_public_key,json=caPublicKey,proto3" json:"ca_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamPrivateKeyAuth) Reset() {
	*x = UpstreamPrivateKeyAuth{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamPrivateKeyAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamPrivateKeyAuth) ProtoMessage() {}

func (x *UpstreamPrivateKeyAuth) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamPrivateKeyAuth.ProtoReflect.Descriptor instead.
func (*UpstreamPrivateKeyAuth) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *UpstreamPrivateKeyAuth) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *UpstreamPrivateKeyAuth) GetCaPublicKey() []byte {
	if x != nil {
		return x.CaPublicKey
	}
	return nil
}

type UpstreamRemoteSignerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          string                 `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamRemoteSignerAuth) Reset() {
	*x = UpstreamRemoteSignerAuth{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamRemoteSignerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamRemoteSignerAuth) ProtoMessage() {}

func (x *UpstreamRemoteSignerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamRemoteSignerAuth.ProtoReflect.Descriptor instead.
func (*UpstreamRemoteSignerAuth) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *UpstreamRemoteSignerAuth) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UpstreamNextPluginAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamNextPluginAuth) Reset() {
	*x = UpstreamNextPluginAuth{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamNextPluginAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamNextPluginAuth) ProtoMessage() {}

func (x *UpstreamNextPluginAuth) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamNextPluginAuth.ProtoReflect.Descriptor instead.
func (*UpstreamNextPluginAuth) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *UpstreamNextPluginAuth) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpstreamRetryCurrentPluginAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamRetryCurrentPluginAuth) Reset() {
	*x = UpstreamRetryCurrentPluginAuth{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamRetryCurrentPluginAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamRetryCurrentPluginAuth) ProtoMessage() {}

func (x *UpstreamRetryCurrentPluginAuth) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamRetryCurrentPluginAuth.ProtoReflect.Descriptor instead.
func (*UpstreamRetryCurrentPluginAuth) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *UpstreamRetryCurrentPluginAuth) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type StartLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniqId        string                 `protobuf:"bytes,1,opt,name=uniq_id,json=uniqId,proto3" json:"uniq_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Tty           bool                   `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLogRequest) Reset() {
	*x = StartLogRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLogRequest) ProtoMessage() {}

func (x *StartLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLogRequest.ProtoReflect.Descriptor instead.
func (*StartLogRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *StartLogRequest) GetUniqId() string {
	if x != nil {
		return x.UniqId
	}
	return ""
}

func (x *StartLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *StartLogRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallbackRequest) Reset() {
	*x = ListCallbackRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallbackRequest) ProtoMessage() {}

func (x *ListCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallbackRequest.ProtoReflect.Descriptor instead.
func (*ListCallbackRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

type ListCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callbacks     []string               `protobuf:"bytes,1,rep,name=callbacks,proto3" json:"callbacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCallbackResponse) Reset() {
	*x = ListCallbackResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCallbackResponse) ProtoMessage() {}

func (x *ListCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCallbackResponse.ProtoReflect.Descriptor instead.
func (*ListCallbackResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ListCallbackResponse) GetCallbacks() []string {
	if x != nil {
		return x.Callbacks
	}
	return nil
}

type NewConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewConnectionRequest) Reset() {
	*x = NewConnectionRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewConnectionRequest) ProtoMessage() {}

func (x *NewConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewConnectionRequest.ProtoReflect.Descriptor instead.
func (*NewConnectionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *NewConnectionRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type NewConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewConnectionResponse) Reset() {
	*x = NewConnectionResponse{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewConnectionResponse) ProtoMessage() {}

func (x *NewConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewConnectionResponse.ProtoReflect.Descriptor instead.
func (*NewConnectionResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

type CreateConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnRequest) Reset() {
	*x = CreateConnRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnRequest) ProtoMessage() {}

func (x *CreateConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnRequest.ProtoReflect.Descriptor instead.
func (*CreateConnRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *CreateConnRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateConnRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type CreateConnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConnResponse) Reset() {
	*x = CreateConnResponse{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConnResponse) ProtoMessage() {}

func (x *CreateConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConnResponse.ProtoReflect.Descriptor instead.
func (*CreateConnResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *CreateConnResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type NextAuthMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextAuthMethodsRequest) Reset() {
	*x = NextAuthMethodsRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextAuthMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextAuthMethodsRequest) ProtoMessage() {}

func (x *NextAuthMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextAuthMethodsRequest.ProtoReflect.Descriptor instead.
func (*NextAuthMethodsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *NextAuthMethodsRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type NextAuthMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []AuthMethod           `protobuf:"varint,1,rep,packed,name=methods,proto3,enum=libplugin.AuthMethod" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextAuthMethodsResponse) Reset() {
	*x = NextAuthMethodsResponse{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextAuthMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextAuthMethodsResponse) ProtoMessage() {}

func (x *NextAuthMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextAuthMethodsResponse.ProtoReflect.Descriptor instead.
func (*NextAuthMethodsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *NextAuthMethodsResponse) GetMethods() []AuthMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

type NoneAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoneAuthRequest) Reset() {
	*x = NoneAuthRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoneAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoneAuthRequest) ProtoMessage() {}

func (x *NoneAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoneAuthRequest.ProtoReflect.Descriptor instead.
func (*NoneAuthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *NoneAuthRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type NoneAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      *Upstream              `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoneAuthResponse) Reset() {
	*x = NoneAuthResponse{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoneAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoneAuthResponse) ProtoMessage() {}

func (x *NoneAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoneAuthResponse.ProtoReflect.Descriptor instead.
func (*NoneAuthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *NoneAuthResponse) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type PasswordAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Password      []byte                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordAuthRequest) Reset() {
	*x = PasswordAuthRequest{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordAuthRequest) ProtoMessage() {}

func (x *PasswordAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordAuthRequest.ProtoReflect.Descriptor instead.
func (*PasswordAuthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *PasswordAuthRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PasswordAuthRequest) GetPassword() []byte {
	if x != nil {
		return x.Password
	}
	return nil
}

type PasswordAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      *Upstream              `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordAuthResponse) Reset() {
	*x = PasswordAuthResponse{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordAuthResponse) ProtoMessage() {}

func (x *PasswordAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordAuthResponse.ProtoReflect.Descriptor instead.
func (*PasswordAuthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *PasswordAuthResponse) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type PublicKeyAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyAuthRequest) Reset() {
	*x = PublicKeyAuthRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyAuthRequest) ProtoMessage() {}

func (x *PublicKeyAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyAuthRequest.ProtoReflect.Descriptor instead.
func (*PublicKeyAuthRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *PublicKeyAuthRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PublicKeyAuthRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type PublicKeyAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      *Upstream              `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyAuthResponse) Reset() {
	*x = PublicKeyAuthResponse{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyAuthResponse) ProtoMessage() {}

func (x *PublicKeyAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyAuthResponse.ProtoReflect.Descriptor instead.
func (*PublicKeyAuthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *PublicKeyAuthResponse) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type KeyboardInteractiveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answers       []string               `protobuf:"bytes,1,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractiveUserResponse) Reset() {
	*x = KeyboardInteractiveUserResponse{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractiveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveUserResponse) ProtoMessage() {}

func (x *KeyboardInteractiveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveUserResponse.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveUserResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *KeyboardInteractiveUserResponse) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

type KeyboardInteractivePromptRequest struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Name          string                                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Instruction   string                                       `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Questions     []*KeyboardInteractivePromptRequest_Question `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractivePromptRequest) Reset() {
	*x = KeyboardInteractivePromptRequest{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractivePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractivePromptRequest) ProtoMessage() {}

func (x *KeyboardInteractivePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractivePromptRequest.ProtoReflect.Descriptor instead.
func (*KeyboardInteractivePromptRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *KeyboardInteractivePromptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyboardInteractivePromptRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *KeyboardInteractivePromptRequest) GetQuestions() []*KeyboardInteractivePromptRequest_Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type KeyboardInteractiveMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractiveMetaRequest) Reset() {
	*x = KeyboardInteractiveMetaRequest{}
	mi := &file_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractiveMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveMetaRequest) ProtoMessage() {}

func (x *KeyboardInteractiveMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveMetaRequest.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveMetaRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{26}
}

type KeyboardInteractiveMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractiveMetaResponse) Reset() {
	*x = KeyboardInteractiveMetaResponse{}
	mi := &file_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractiveMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveMetaResponse) ProtoMessage() {}

func (x *KeyboardInteractiveMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveMetaResponse.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveMetaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *KeyboardInteractiveMetaResponse) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type KeyboardInteractiveFinishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstream      *Upstream              `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractiveFinishRequest) Reset() {
	*x = KeyboardInteractiveFinishRequest{}
	mi := &file_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractiveFinishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveFinishRequest) ProtoMessage() {}

func (x *KeyboardInteractiveFinishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveFinishRequest.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveFinishRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *KeyboardInteractiveFinishRequest) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type KeyboardInteractiveAuthMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*KeyboardInteractiveAuthMessage_PromptRequest
	//	*KeyboardInteractiveAuthMessage_UserResponse
	//	*KeyboardInteractiveAuthMessage_MetaRequest
	//	*KeyboardInteractiveAuthMessage_MetaResponse
	//	*KeyboardInteractiveAuthMessage_FinishRequest
	Message       isKeyboardInteractiveAuthMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractiveAuthMessage) Reset() {
	*x = KeyboardInteractiveAuthMessage{}
	mi := &file_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractiveAuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractiveAuthMessage) ProtoMessage() {}

func (x *KeyboardInteractiveAuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractiveAuthMessage.ProtoReflect.Descriptor instead.
func (*KeyboardInteractiveAuthMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *KeyboardInteractiveAuthMessage) GetMessage() isKeyboardInteractiveAuthMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *KeyboardInteractiveAuthMessage) GetPromptRequest() *KeyboardInteractivePromptRequest {
	if x != nil {
		if x, ok := x.Message.(*KeyboardInteractiveAuthMessage_PromptRequest); ok {
			return x.PromptRequest
		}
	}
	return nil
}

func (x *KeyboardInteractiveAuthMessage) GetUserResponse() *KeyboardInteractiveUserResponse {
	if x != nil {
		if x, ok := x.Message.(*KeyboardInteractiveAuthMessage_UserResponse); ok {
			return x.UserResponse
		}
	}
	return nil
}

func (x *KeyboardInteractiveAuthMessage) GetMetaRequest() *KeyboardInteractiveMetaRequest {
	if x != nil {
		if x, ok := x.Message.(*KeyboardInteractiveAuthMessage_MetaRequest); ok {
			return x.MetaRequest
		}
	}
	return nil
}

func (x *KeyboardInteractiveAuthMessage) GetMetaResponse() *KeyboardInteractiveMetaResponse {
	if x != nil {
		if x, ok := x.Message.(*KeyboardInteractiveAuthMessage_MetaResponse); ok {
			return x.MetaResponse
		}
	}
	return nil
}

func (x *KeyboardInteractiveAuthMessage) GetFinishRequest() *KeyboardInteractiveFinishRequest {
	if x != nil {
		if x, ok := x.Message.(*KeyboardInteractiveAuthMessage_FinishRequest); ok {
			return x.FinishRequest
		}
	}
	return nil
}

type isKeyboardInteractiveAuthMessage_Message interface {
	isKeyboardInteractiveAuthMessage_Message()
}

type KeyboardInteractiveAuthMessage_PromptRequest struct {
	PromptRequest *KeyboardInteractivePromptRequest `protobuf:"bytes,1,opt,name=prompt_request,json=promptRequest,proto3,oneof"`
}

type KeyboardInteractiveAuthMessage_UserResponse struct {
	UserResponse *KeyboardInteractiveUserResponse `protobuf:"bytes,2,opt,name=user_response,json=userResponse,proto3,oneof"`
}

type KeyboardInteractiveAuthMessage_MetaRequest struct {
	MetaRequest *KeyboardInteractiveMetaRequest `protobuf:"bytes,3,opt,name=meta_request,json=metaRequest,proto3,oneof"`
}

type KeyboardInteractiveAuthMessage_MetaResponse struct {
	MetaResponse *KeyboardInteractiveMetaResponse `protobuf:"bytes,4,opt,name=meta_response,json=metaResponse,proto3,oneof"`
}

type KeyboardInteractiveAuthMessage_FinishRequest struct {
	FinishRequest *KeyboardInteractiveFinishRequest `protobuf:"bytes,5,opt,name=finish_request,json=finishRequest,proto3,oneof"`
}

func (*KeyboardInteractiveAuthMessage_PromptRequest) isKeyboardInteractiveAuthMessage_Message() {}

func (*KeyboardInteractiveAuthMessage_UserResponse) isKeyboardInteractiveAuthMessage_Message() {}

func (*KeyboardInteractiveAuthMessage_MetaRequest) isKeyboardInteractiveAuthMessage_Message() {}

func (*KeyboardInteractiveAuthMessage_MetaResponse) isKeyboardInteractiveAuthMessage_Message() {}

func (*KeyboardInteractiveAuthMessage_FinishRequest) isKeyboardInteractiveAuthMessage_Message() {}

type UpstreamAuthFailureNoticeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meta           *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Method         string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	AllowedMethods []AuthMethod           `protobuf:"varint,4,rep,packed,name=allowed_methods,json=allowedMethods,proto3,enum=libplugin.AuthMethod" json:"allowed_methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpstreamAuthFailureNoticeRequest) Reset() {
	*x = UpstreamAuthFailureNoticeRequest{}
	mi := &file_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamAuthFailureNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamAuthFailureNoticeRequest) ProtoMessage() {}

func (x *UpstreamAuthFailureNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamAuthFailureNoticeRequest.ProtoReflect.Descriptor instead.
func (*UpstreamAuthFailureNoticeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *UpstreamAuthFailureNoticeRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UpstreamAuthFailureNoticeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UpstreamAuthFailureNoticeRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpstreamAuthFailureNoticeRequest) GetAllowedMethods() []AuthMethod {
	if x != nil {
		return x.AllowedMethods
	}
	return nil
}

type UpstreamAuthFailureNoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamAuthFailureNoticeResponse) Reset() {
	*x = UpstreamAuthFailureNoticeResponse{}
	mi := &file_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamAuthFailureNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamAuthFailureNoticeResponse) ProtoMessage() {}

func (x *UpstreamAuthFailureNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamAuthFailureNoticeResponse.ProtoReflect.Descriptor instead.
func (*UpstreamAuthFailureNoticeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{31}
}

type BannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerRequest) Reset() {
	*x = BannerRequest{}
	mi := &file_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRequest) ProtoMessage() {}

func (x *BannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRequest.ProtoReflect.Descriptor instead.
func (*BannerRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *BannerRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *BannerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyHostKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Netaddress    string                 `protobuf:"bytes,4,opt,name=netaddress,proto3" json:"netaddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyHostKeyRequest) Reset() {
	*x = VerifyHostKeyRequest{}
	mi := &file_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyHostKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyHostKeyRequest) ProtoMessage() {}

func (x *VerifyHostKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyHostKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyHostKeyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *VerifyHostKeyRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *VerifyHostKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *VerifyHostKeyRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *VerifyHostKeyRequest) GetNetaddress() string {
	if x != nil {
		return x.Netaddress
	}
	return ""
}

type VerifyHostKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyHostKeyResponse) Reset() {
	*x = VerifyHostKeyResponse{}
	mi := &file_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyHostKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyHostKeyResponse) ProtoMessage() {}

func (x *VerifyHostKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyHostKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyHostKeyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *VerifyHostKeyResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type PipeStartNoticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeStartNoticeRequest) Reset() {
	*x = PipeStartNoticeRequest{}
	mi := &file_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeStartNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeStartNoticeRequest) ProtoMessage() {}

func (x *PipeStartNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeStartNoticeRequest.ProtoReflect.Descriptor instead.
func (*PipeStartNoticeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *PipeStartNoticeRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PipeStartNoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeStartNoticeResponse) Reset() {
	*x = PipeStartNoticeResponse{}
	mi := &file_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeStartNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeStartNoticeResponse) ProtoMessage() {}

func (x *PipeStartNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeStartNoticeResponse.ProtoReflect.Descriptor instead.
func (*PipeStartNoticeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{37}
}

type PipeErrorNoticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ConnMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeErrorNoticeRequest) Reset() {
	*x = PipeErrorNoticeRequest{}
	mi := &file_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeErrorNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeErrorNoticeRequest) ProtoMessage() {}

func (x *PipeErrorNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeErrorNoticeRequest.ProtoReflect.Descriptor instead.
func (*PipeErrorNoticeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{38}
}

func (x *PipeErrorNoticeRequest) GetMeta() *ConnMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PipeErrorNoticeRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PipeErrorNoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeErrorNoticeResponse) Reset() {
	*x = PipeErrorNoticeResponse{}
	mi := &file_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeErrorNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeErrorNoticeResponse) ProtoMessage() {}

func (x *PipeErrorNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeErrorNoticeResponse.ProtoReflect.Descriptor instead.
func (*PipeErrorNoticeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{39}
}

type PipeCreateErrorNoticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddr      string                 `protobuf:"bytes,1,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeCreateErrorNoticeRequest) Reset() {
	*x = PipeCreateErrorNoticeRequest{}
	mi := &file_plugin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeCreateErrorNoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeCreateErrorNoticeRequest) ProtoMessage() {}

func (x *PipeCreateErrorNoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeCreateErrorNoticeRequest.ProtoReflect.Descriptor instead.
func (*PipeCreateErrorNoticeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{40}
}

func (x *PipeCreateErrorNoticeRequest) GetFromAddr() string {
	if x != nil {
		return x.FromAddr
	}
	return ""
}

func (x *PipeCreateErrorNoticeRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PipeCreateErrorNoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeCreateErrorNoticeResponse) Reset() {
	*x = PipeCreateErrorNoticeResponse{}
	mi := &file_plugin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeCreateErrorNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeCreateErrorNoticeResponse) ProtoMessage() {}

func (x *PipeCreateErrorNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeCreateErrorNoticeResponse.ProtoReflect.Descriptor instead.
func (*PipeCreateErrorNoticeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{41}
}

type KeyboardInteractivePromptRequest_Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Echo          bool                   `protobuf:"varint,2,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyboardInteractivePromptRequest_Question) Reset() {
	*x = KeyboardInteractivePromptRequest_Question{}
	mi := &file_plugin_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyboardInteractivePromptRequest_Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyboardInteractivePromptRequest_Question) ProtoMessage() {}

func (x *KeyboardInteractivePromptRequest_Question) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyboardInteractivePromptRequest_Question.ProtoReflect.Descriptor instead.
func (*KeyboardInteractivePromptRequest_Question) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25, 0}
}

func (x *KeyboardInteractivePromptRequest_Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *KeyboardInteractivePromptRequest_Question) GetEcho() bool {
	if x != nil {
		return x.Echo
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\tlibplugin\"\xd9\x01\n" +
	"\bConnMeta\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x1b\n" +
	"\tfrom_addr\x18\x02 \x01(\tR\bfromAddr\x12\x17\n" +
	"\auniq_id\x18\x03 \x01(\tR\x06uniqId\x12=\n" +
	"\bmetadata\x18\x04 \x03(\v2!.libplugin.ConnMeta.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x04\n" +
	"\bUpstream\x12\x16\n" +
	"\x04host\x18\x01 \x01(\tB\x02\x18\x01R\x04host\x12\x16\n" +
	"\x04port\x18\x02 \x01(\x05B\x02\x18\x01R\x04port\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12&\n" +
	"\x0fignore_host_key\x18\x04 \x01(\bR\rignoreHostKey\x12\x10\n" +
	"\x03uri\x18\x05 \x01(\tR\x03uri\x121\n" +
	"\x04none\x18d \x01(\v2\x1b.libplugin.UpstreamNoneAuthH\x00R\x04none\x12=\n" +
	"\bpassword\x18e \x01(\v2\x1f.libplugin.UpstreamPasswordAuthH\x00R\bpassword\x12D\n" +
	"\vprivate_key\x18f \x01(\v2!.libplugin.UpstreamPrivateKeyAuthH\x00R\n" +
	"privateKey\x12J\n" +
	"\rremote_signer\x18g \x01(\v2#.libplugin.UpstreamRemoteSignerAuthH\x00R\fremoteSigner\x12E\n" +
	"\vnext_plugin\x18\xc8\x01 \x01(\v2!.libplugin.UpstreamNextPluginAuthH\x00R\n" +
	"nextPlugin\x12^\n" +
	"\x14retry_current_plugin\x18\xc9\x01 \x01(\v2).libplugin.UpstreamRetryCurrentPluginAuthH\x00R\x12retryCurrentPluginB\x06\n" +
	"\x04auth\"\x12\n" +
	"\x10UpstreamNoneAuth\"2\n" +
	"\x14UpstreamPasswordAuth\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"]\n" +
	"\x16UpstreamPrivateKeyAuth\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\fR\n" +
	"privateKey\x12\"\n" +
	"\rca_public_key\x18\x02 \x01(\fR\vcaPublicKey\".\n" +
	"\x18UpstreamRemoteSignerAuth\x12\x12\n" +
	"\x04meta\x18\x01 \x01(\tR\x04meta\"\x92\x01\n" +
	"\x16UpstreamNextPluginAuth\x12?\n" +
	"\x04meta\x18\x01 \x03(\v2+.libplugin.UpstreamNextPluginAuth.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x1eUpstreamRetryCurrentPluginAuth\x12G\n" +
	"\x04meta\x18\x01 \x03(\v23.libplugin.UpstreamRetryCurrentPluginAuth.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0fStartLogRequest\x12\x17\n" +
	"\auniq_id\x18\x01 \x01(\tR\x06uniqId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\"\x1f\n" +
	"\x03Log\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13ListCallbackRequest\"4\n" +
	"\x14ListCallbackResponse\x12\x1c\n" +
	"\tcallbacks\x18\x01 \x03(\tR\tcallbacks\"?\n" +
	"\x14NewConnectionRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\"\x17\n" +
	"\x15NewConnectionResponse\"N\n" +
	"\x11CreateConnRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"&\n" +
	"\x12CreateConnResponse\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"A\n" +
	"\x16NextAuthMethodsRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\"J\n" +
	"\x17NextAuthMethodsResponse\x12/\n" +
	"\amethods\x18\x01 \x03(\x0e2\x15.libplugin.AuthMethodR\amethods\":\n" +
	"\x0fNoneAuthRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\"C\n" +
	"\x10NoneAuthResponse\x12/\n" +
	"\bupstream\x18\x01 \x01(\v2\x13.libplugin.UpstreamR\bupstream\"Z\n" +
	"\x13PasswordAuthRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\fR\bpassword\"G\n" +
	"\x14PasswordAuthResponse\x12/\n" +
	"\bupstream\x18\x01 \x01(\v2\x13.libplugin.UpstreamR\bupstream\"^\n" +
	"\x14PublicKeyAuthRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"H\n" +
	"\x15PublicKeyAuthResponse\x12/\n" +
	"\bupstream\x18\x01 \x01(\v2\x13.libplugin.UpstreamR\bupstream\";\n" +
	"\x1fKeyboardInteractiveUserResponse\x12\x18\n" +
	"\aanswers\x18\x01 \x03(\tR\aanswers\"\xe0\x01\n" +
	" KeyboardInteractivePromptRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\x12R\n" +
	"\tquestions\x18\x03 \x03(\v24.libplugin.KeyboardInteractivePromptRequest.QuestionR\tquestions\x1a2\n" +
	"\bQuestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04echo\x18\x02 \x01(\bR\x04echo\" \n" +
	"\x1eKeyboardInteractiveMetaRequest\"J\n" +
	"\x1fKeyboardInteractiveMetaResponse\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\"S\n" +
	" KeyboardInteractiveFinishRequest\x12/\n" +
	"\bupstream\x18\x01 \x01(\v2\x13.libplugin.UpstreamR\bupstream\"\xcd\x03\n" +
	"\x1eKeyboardInteractiveAuthMessage\x12T\n" +
	"\x0eprompt_request\x18\x01 \x01(\v2+.libplugin.KeyboardInteractivePromptRequestH\x00R\rpromptRequest\x12Q\n" +
	"\ruser_response\x18\x02 \x01(\v2*.libplugin.KeyboardInteractiveUserResponseH\x00R\fuserResponse\x12N\n" +
	"\fmeta_request\x18\x03 \x01(\v2).libplugin.KeyboardInteractiveMetaRequestH\x00R\vmetaRequest\x12Q\n" +
	"\rmeta_response\x18\x04 \x01(\v2*.libplugin.KeyboardInteractiveMetaResponseH\x00R\fmetaResponse\x12T\n" +
	"\x0efinish_request\x18\x05 \x01(\v2+.libplugin.KeyboardInteractiveFinishRequestH\x00R\rfinishRequestB\t\n" +
	"\amessage\"\xb9\x01\n" +
	" UpstreamAuthFailureNoticeRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12>\n" +
	"\x0fallowed_methods\x18\x04 \x03(\x0e2\x15.libplugin.AuthMethodR\x0eallowedMethods\"#\n" +
	"!UpstreamAuthFailureNoticeResponse\"8\n" +
	"\rBannerRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\"*\n" +
	"\x0eBannerResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8d\x01\n" +
	"\x14VerifyHostKeyRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1e\n" +
	"\n" +
	"netaddress\x18\x04 \x01(\tR\n" +
	"netaddress\"3\n" +
	"\x15VerifyHostKeyResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\"A\n" +
	"\x16PipeStartNoticeRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\"\x19\n" +
	"\x17PipeStartNoticeResponse\"W\n" +
	"\x16PipeErrorNoticeRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.libplugin.ConnMetaR\x04meta\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x19\n" +
	"\x17PipeErrorNoticeResponse\"Q\n" +
	"\x1cPipeCreateErrorNoticeRequest\x12\x1b\n" +
	"\tfrom_addr\x18\x01 \x01(\tR\bfromAddr\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1f\n" +
	"\x1dPipeCreateErrorNoticeResponse*M\n" +
	"\n" +
	"AuthMethod\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bPASSWORD\x10\x01\x12\r\n" +
	"\tPUBLICKEY\x10\x02\x12\x18\n" +
	"\x14KEYBOARD_INTERACTIVE\x10\x032\xb9\n" +
	"\n" +
	"\x0eSshPiperPlugin\x126\n" +
	"\x04Logs\x12\x1a.libplugin.StartLogRequest\x1a\x0e.libplugin.Log\"\x000\x01\x12R\n" +
	"\rListCallbacks\x12\x1e.libplugin.ListCallbackRequest\x1a\x1f.libplugin.ListCallbackResponse\"\x00\x12T\n" +
	"\rNewConnection\x12\x1f.libplugin.NewConnectionRequest\x1a .libplugin.NewConnectionResponse\"\x00\x12K\n" +
	"\n" +
	"CreateConn\x12\x1c.libplugin.CreateConnRequest\x1a\x1d.libplugin.CreateConnResponse\"\x00\x12Z\n" +
	"\x0fNextAuthMethods\x12!.libplugin.NextAuthMethodsRequest\x1a\".libplugin.NextAuthMethodsResponse\"\x00\x12E\n" +
	"\bNoneAuth\x12\x1a.libplugin.NoneAuthRequest\x1a\x1b.libplugin.NoneAuthResponse\"\x00\x12Q\n" +
	"\fPasswordAuth\x12\x1e.libplugin.PasswordAuthRequest\x1a\x1f.libplugin.PasswordAuthResponse\"\x00\x12T\n" +
	"\rPublicKeyAuth\x12\x1f.libplugin.PublicKeyAuthRequest\x1a .libplugin.PublicKeyAuthResponse\"\x00\x12u\n" +
	"\x17KeyboardInteractiveAuth\x12).libplugin.KeyboardInteractiveAuthMessage\x1a).libplugin.KeyboardInteractiveAuthMessage\"\x00(\x010\x01\x12x\n" +
	"\x19UpstreamAuthFailureNotice\x12+.libplugin.UpstreamAuthFailureNoticeRequest\x1a,.libplugin.UpstreamAuthFailureNoticeResponse\"\x00\x12?\n" +
	"\x06Banner\x12\x18.libplugin.BannerRequest\x1a\x19.libplugin.BannerResponse\"\x00\x12T\n" +
	"\rVerifyHostKey\x12\x1f.libplugin.VerifyHostKeyRequest\x1a .libplugin.VerifyHostKeyResponse\"\x00\x12l\n" +
	"\x15PipeCreateErrorNotice\x12'.libplugin.PipeCreateErrorNoticeRequest\x1a(.libplugin.PipeCreateErrorNoticeResponse\"\x00\x12Z\n" +
	"\x0fPipeStartNotice\x12!.libplugin.PipeStartNoticeRequest\x1a\".libplugin.PipeStartNoticeResponse\"\x00\x12Z\n" +
	"\x0fPipeErrorNotice\x12!.libplugin.PipeErrorNoticeRequest\x1a\".libplugin.PipeErrorNoticeResponse\"\x00B%Z#github.com/tg123/sshpiper/libpluginb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_plugin_proto_goTypes = []any{
	(AuthMethod)(0),                                   // 0: libplugin.AuthMethod
	(*ConnMeta)(nil),                                  // 1: libplugin.ConnMeta
	(*Upstream)(nil),                                  // 2: libplugin.Upstream
	(*UpstreamNoneAuth)(nil),                          // 3: libplugin.UpstreamNoneAuth
	(*UpstreamPasswordAuth)(nil),                      // 4: libplugin.UpstreamPasswordAuth
	(*UpstreamPrivateKeyAuth)(nil),                    // 5: libplugin.UpstreamPrivateKeyAuth
	(*UpstreamRemoteSignerAuth)(nil),                  // 6: libplugin.UpstreamRemoteSignerAuth
	(*UpstreamNextPluginAuth)(nil),                    // 7: libplugin.UpstreamNextPluginAuth
	(*UpstreamRetryCurrentPluginAuth)(nil),            // 8: libplugin.UpstreamRetryCurrentPluginAuth
	(*StartLogRequest)(nil),                           // 9: libplugin.StartLogRequest
	(*Log)(nil),                                       // 10: libplugin.Log
	(*ListCallbackRequest)(nil),                       // 11: libplugin.ListCallbackRequest
	(*ListCallbackResponse)(nil),                      // 12: libplugin.ListCallbackResponse
	(*NewConnectionRequest)(nil),                      // 13: libplugin.NewConnectionRequest
	(*NewConnectionResponse)(nil),                     // 14: libplugin.NewConnectionResponse
	(*CreateConnRequest)(nil),                         // 15: libplugin.CreateConnRequest
	(*CreateConnResponse)(nil),                        // 16: libplugin.CreateConnResponse
	(*NextAuthMethodsRequest)(nil),                    // 17: libplugin.NextAuthMethodsRequest
	(*NextAuthMethodsResponse)(nil),                   // 18: libplugin.NextAuthMethodsResponse
	(*NoneAuthRequest)(nil),                           // 19: libplugin.NoneAuthRequest
	(*NoneAuthResponse)(nil),                          // 20: libplugin.NoneAuthResponse
	(*PasswordAuthRequest)(nil),                       // 21: libplugin.PasswordAuthRequest
	(*PasswordAuthResponse)(nil),                      // 22: libplugin.PasswordAuthResponse
	(*PublicKeyAuthRequest)(nil),                      // 23: libplugin.PublicKeyAuthRequest
	(*PublicKeyAuthResponse)(nil),                     // 24: libplugin.PublicKeyAuthResponse
	(*KeyboardInteractiveUserResponse)(nil),           // 25: libplugin.KeyboardInteractiveUserResponse
	(*KeyboardInteractivePromptRequest)(nil),          // 26: libplugin.KeyboardInteractivePromptRequest
	(*KeyboardInteractiveMetaRequest)(nil),            // 27: libplugin.KeyboardInteractiveMetaRequest
	(*KeyboardInteractiveMetaResponse)(nil),           // 28: libplugin.KeyboardInteractiveMetaResponse
	(*KeyboardInteractiveFinishRequest)(nil),          // 29: libplugin.KeyboardInteractiveFinishRequest
	(*KeyboardInteractiveAuthMessage)(nil),            // 30: libplugin.KeyboardInteractiveAuthMessage
	(*UpstreamAuthFailureNoticeRequest)(nil),          // 31: libplugin.UpstreamAuthFailureNoticeRequest
	(*UpstreamAuthFailureNoticeResponse)(nil),         // 32: libplugin.UpstreamAuthFailureNoticeResponse
	(*BannerRequest)(nil),                             // 33: libplugin.BannerRequest
	(*BannerResponse)(nil),                            // 34: libplugin.BannerResponse
	(*VerifyHostKeyRequest)(nil),                      // 35: libplugin.VerifyHostKeyRequest
	(*VerifyHostKeyResponse)(nil),                     // 36: libplugin.VerifyHostKeyResponse
	(*PipeStartNoticeRequest)(nil),                    // 37: libplugin.PipeStartNoticeRequest
	(*PipeStartNoticeResponse)(nil),                   // 38: libplugin.PipeStartNoticeResponse
	(*PipeErrorNoticeRequest)(nil),                    // 39: libplugin.PipeErrorNoticeRequest
	(*PipeErrorNoticeResponse)(nil),                   // 40: libplugin.PipeErrorNoticeResponse
	(*PipeCreateErrorNoticeRequest)(nil),              // 41: libplugin.PipeCreateErrorNoticeRequest
	(*PipeCreateErrorNoticeResponse)(nil),             // 42: libplugin.PipeCreateErrorNoticeResponse
	nil,                                               // 43: libplugin.ConnMeta.MetadataEntry
	nil,                                               // 44: libplugin.UpstreamNextPluginAuth.MetaEntry
	nil,                                               // 45: libplugin.UpstreamRetryCurrentPluginAuth.MetaEntry
	(*KeyboardInteractivePromptRequest_Question)(nil), // 46: libplugin.KeyboardInteractivePromptRequest.Question
}
var file_plugin_proto_depIdxs = []int32{
	43, // 0: libplugin.ConnMeta.metadata:type_name -> libplugin.ConnMeta.MetadataEntry
	3,  // 1: libplugin.Upstream.none:type_name -> libplugin.UpstreamNoneAuth
	4,  // 2: libplugin.Upstream.password:type_name -> libplugin.UpstreamPasswordAuth
	5,  // 3: libplugin.Upstream.private_key:type_name -> libplugin.UpstreamPrivateKeyAuth
	6,  // 4: libplugin.Upstream.remote_signer:type_name -> libplugin.UpstreamRemoteSignerAuth
	7,  // 5: libplugin.Upstream.next_plugin:type_name -> libplugin.UpstreamNextPluginAuth
	8,  // 6: libplugin.Upstream.retry_current_plugin:type_name -> libplugin.UpstreamRetryCurrentPluginAuth
	44, // 7: libplugin.UpstreamNextPluginAuth.meta:type_name -> libplugin.UpstreamNextPluginAuth.MetaEntry
	45, // 8: libplugin.UpstreamRetryCurrentPluginAuth.meta:type_name -> libplugin.UpstreamRetryCurrentPluginAuth.MetaEntry
	1,  // 9: libplugin.NewConnectionRequest.meta:type_name -> libplugin.ConnMeta
	1,  // 10: libplugin.CreateConnRequest.meta:type_name -> libplugin.ConnMeta
	1,  // 11: libplugin.NextAuthMethodsRequest.meta:type_name -> libplugin.ConnMeta
	0,  // 12: libplugin.NextAuthMethodsResponse.methods:type_name -> libplugin.AuthMethod
	1,  // 13: libplugin.NoneAuthRequest.meta:type_name -> libplugin.ConnMeta
	2,  // 14: libplugin.NoneAuthResponse.upstream:type_name -> libplugin.Upstream
	1,  // 15: libplugin.PasswordAuthRequest.meta:type_name -> libplugin.ConnMeta
	2,  // 16: libplugin.PasswordAuthResponse.upstream:type_name -> libplugin.Upstream
	1,  // 17: libplugin.PublicKeyAuthRequest.meta:type_name -> libplugin.ConnMeta
	2,  // 18: libplugin.PublicKeyAuthResponse.upstream:type_name -> libplugin.Upstream
	46, // 19: libplugin.KeyboardInteractivePromptRequest.questions:type_name -> libplugin.KeyboardInteractivePromptRequest.Question
	1,  // 20: libplugin.KeyboardInteractiveMetaResponse.meta:type_name -> libplugin.ConnMeta
	2,  // 21: libplugin.KeyboardInteractiveFinishRequest.upstream:type_name -> libplugin.Upstream
	26, // 22: libplugin.KeyboardInteractiveAuthMessage.prompt_request:type_name -> libplugin.KeyboardInteractivePromptRequest
	25, // 23: libplugin.KeyboardInteractiveAuthMessage.user_response:type_name -> libplugin.KeyboardInteractiveUserResponse
	27, // 24: libplugin.KeyboardInteractiveAuthMessage.meta_request:type_name -> libplugin.KeyboardInteractiveMetaRequest
	28, // 25: libplugin.KeyboardInteractiveAuthMessage.meta_response:type_name -> libplugin.KeyboardInteractiveMetaResponse
	29, // 26: libplugin.KeyboardInteractiveAuthMessage.finish_request:type_name -> libplugin.KeyboardInteractiveFinishRequest
	1,  // 27: libplugin.UpstreamAuthFailureNoticeRequest.meta:type_name -> libplugin.ConnMeta
	0,  // 28: libplugin.UpstreamAuthFailureNoticeRequest.allowed_methods:type_name -> libplugin.AuthMethod
	1,  // 29: libplugin.BannerRequest.meta:type_name -> libplugin.ConnMeta
	1,  // 30: libplugin.VerifyHostKeyRequest.meta:type_name -> libplugin.ConnMeta
	1,  // 31: libplugin.PipeStartNoticeRequest.meta:type_name -> libplugin.ConnMeta
	1,  // 32: libplugin.PipeErrorNoticeRequest.meta:type_name -> libplugin.ConnMeta
	9,  // 33: libplugin.SshPiperPlugin.Logs:input_type -> libplugin.StartLogRequest
	11, // 34: libplugin.SshPiperPlugin.ListCallbacks:input_type -> libplugin.ListCallbackRequest
	13, // 35: libplugin.SshPiperPlugin.NewConnection:input_type -> libplugin.NewConnectionRequest
	15, // 36: libplugin.SshPiperPlugin.CreateConn:input_type -> libplugin.CreateConnRequest
	17, // 37: libplugin.SshPiperPlugin.NextAuthMethods:input_type -> libplugin.NextAuthMethodsRequest
	19, // 38: libplugin.SshPiperPlugin.NoneAuth:input_type -> libplugin.NoneAuthRequest
	21, // 39: libplugin.SshPiperPlugin.PasswordAuth:input_type -> libplugin.PasswordAuthRequest
	23, // 40: libplugin.SshPiperPlugin.PublicKeyAuth:input_type -> libplugin.PublicKeyAuthRequest
	30, // 41: libplugin.SshPiperPlugin.KeyboardInteractiveAuth:input_type -> libplugin.KeyboardInteractiveAuthMessage
	31, // 42: libplugin.SshPiperPlugin.UpstreamAuthFailureNotice:input_type -> libplugin.UpstreamAuthFailureNoticeRequest
	33, // 43: libplugin.SshPiperPlugin.Banner:input_type -> libplugin.BannerRequest
	35, // 44: libplugin.SshPiperPlugin.VerifyHostKey:input_type -> libplugin.VerifyHostKeyRequest
	41, // 45: libplugin.SshPiperPlugin.PipeCreateErrorNotice:input_type -> libplugin.PipeCreateErrorNoticeRequest
	37, // 46: libplugin.SshPiperPlugin.PipeStartNotice:input_type -> libplugin.PipeStartNoticeRequest
	39, // 47: libplugin.SshPiperPlugin.PipeErrorNotice:input_type -> libplugin.PipeErrorNoticeRequest
	10, // 48: libplugin.SshPiperPlugin.Logs:output_type -> libplugin.Log
	12, // 49: libplugin.SshPiperPlugin.ListCallbacks:output_type -> libplugin.ListCallbackResponse
	14, // 50: libplugin.SshPiperPlugin.NewConnection:output_type -> libplugin.NewConnectionResponse
	16, // 51: libplugin.SshPiperPlugin.CreateConn:output_type -> libplugin.CreateConnResponse
	18, // 52: libplugin.SshPiperPlugin.NextAuthMethods:output_type -> libplugin.NextAuthMethodsResponse
	20, // 53: libplugin.SshPiperPlugin.NoneAuth:output_type -> libplugin.NoneAuthResponse
	22, // 54: libplugin.SshPiperPlugin.PasswordAuth:output_type -> libplugin.PasswordAuthResponse
	24, // 55: libplugin.SshPiperPlugin.PublicKeyAuth:output_type -> libplugin.PublicKeyAuthResponse
	30, // 56: libplugin.SshPiperPlugin.KeyboardInteractiveAuth:output_type -> libplugin.KeyboardInteractiveAuthMessage
	32, // 57: libplugin.SshPiperPlugin.UpstreamAuthFailureNotice:output_type -> libplugin.UpstreamAuthFailureNoticeResponse
	34, // 58: libplugin.SshPiperPlugin.Banner:output_type -> libplugin.BannerResponse
	36, // 59: libplugin.SshPiperPlugin.VerifyHostKey:output_type -> libplugin.VerifyHostKeyResponse
	42, // 60: libplugin.SshPiperPlugin.PipeCreateErrorNotice:output_type -> libplugin.PipeCreateErrorNoticeResponse
	38, // 61: libplugin.SshPiperPlugin.PipeStartNotice:output_type -> libplugin.PipeStartNoticeResponse
	40, // 62: libplugin.SshPiperPlugin.PipeErrorNotice:output_type -> libplugin.PipeErrorNoticeResponse
	48, // [48:63] is the sub-list for method output_type
	33, // [33:48] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*Upstream_None)(nil),
		(*Upstream_Password)(nil),
		(*Upstream_PrivateKey)(nil),
		(*Upstream_RemoteSigner)(nil),
		(*Upstream_NextPlugin)(nil),
		(*Upstream_RetryCurrentPlugin)(nil),
	}
	file_plugin_proto_msgTypes[29].OneofWrappers = []any{
		(*KeyboardInteractiveAuthMessage_PromptRequest)(nil),
		(*KeyboardInteractiveAuthMessage_UserResponse)(nil),
		(*KeyboardInteractiveAuthMessage_MetaRequest)(nil),
		(*KeyboardInteractiveAuthMessage_MetaResponse)(nil),
		(*KeyboardInteractiveAuthMessage_FinishRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
