
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/vvanpo/golang-pam"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
  source = "https://github.com/tg123/sshpiper.crypto"

[[constraint]]
  version = "v1.9.1"
  name = "github.com/jinzhu/gorm"

[[constraint]]
  version = "v1.4.0"
  name = "github.com/jessevdk/go-flags"
