name: sshpiperd
version: 0.5.0
summary: The missing reverse proxy for ssh scp
description: |
  SSH Piper works as a proxy-like ware, and route connections by username, src ip , etc.

grade: stable
confinement: strict

parts:
  sshpiperd:
    plugin: dump
    source: /build

apps:
  sshpiperd-daemon:
    command: sshpiperd daemon --config $SNAP_DATA/sshpiperd.ini
    plugs: [network-bind]
    daemon: simple
  sshpiperd:
    command: sshpiperd --config $SNAP_DATA/sshpiperd.ini

hooks:
  configure:
    plugs: [home]
  install:
    plugs: [home]
