version: '3'

services:
  host1:
    image: rastasheep/ubuntu-sshd
    volumes:
      - host1ssh:/root/.ssh
      - names:/names
  host2:
    image: rastasheep/ubuntu-sshd
    volumes:
      - names:/names
  client:
    image: valudio/docker-sshpass
    volumes:
      - workingdir:/workingdir
      - localkey:/local
      - host1ssh:/host1
      - names:/names
      - ./test.sh:/test.sh
      - ./wait.sh:/wait.sh
    links:
      - "piper:piper"
      - "piper_sqlite:piper_sqlite"
      - "piper_mysql:piper_mysql"
      - "piper_pg:piper_pg"
    command:
      - "/bin/sh"
      - "/test.sh"
    depends_on:
      - piper
      - piper_mysql
      - piper_pg
      - piper_mssql
  piper:
    environment:
      - "SSHPIPERD_UPSTREAM_WORKINGDIR_NOCHECKPERM=true"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
    volumes:
      - workingdir:/var/sshpiper
      - ./piper.sh:/piper.sh
      - ./wait.sh:/wait.sh
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - host1
      - host2
  piper_sqlite:
    environment:
      - "SSHPIPERD_UPSTREAM_DRIVER=sqlite"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
    volumes:
      - workingdir:/var/sshpiper
      - ./piper.sh:/piper.sh
      - ./wait.sh:/wait.sh
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - host1
      - host2
  piper_mysql:
    environment:
      - "WAIT_HOST=mysql"
      - "WAIT_PORT=3306"
      - "SSHPIPERD_UPSTREAM_DRIVER=mysql"
      - "SSHPIPERD_UPSTREAM_MYSQL_HOST=mysql"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
      - "mysql:mysql"
    volumes:
      - ./piper.sh:/piper.sh
      - workingdir:/var/sshpiper
      - ./wait.sh:/wait.sh
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - mysql
      - host1
      - host2
  mysql:
    image: mysql
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=sshpiper"
    tmpfs:
      - /var/lib/mysql
  piper_pg:
    environment:
      - "WAIT_HOST=postgres"
      - "WAIT_PORT=5432"
      - "SSHPIPERD_UPSTREAM_DRIVER=postgres"
      - "SSHPIPERD_UPSTREAM_POSTGRES_HOST=postgres"
      - "SSHPIPERD_UPSTREAM_POSTGRES_SSLMODE=disable"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
      - "postgres:postgres"
    volumes:
      - ./piper.sh:/piper.sh
      - workingdir:/var/sshpiper
      - ./wait.sh:/wait.sh
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - postgres
      - host1
      - host2
  postgres:
    image: postgres
    environment:
      - "POSTGRES_DB=sshpiper"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    tmpfs:
      - /var/lib/postgresql/data
  piper_mssql:
    environment:
      - "WAIT_HOST=mssql"
      - "WAIT_PORT=1433"
      - "SSHPIPERD_UPSTREAM_DRIVER=mssql"
      - "SSHPIPERD_UPSTREAM_MSSQL_HOST=mssql"
      - "SSHPIPERD_UPSTREAM_MSSQL_PASSWORD=yourStrong(!)Password"
      - "SSHPIPERD_UPSTREAM_MSSQL_DBNAME=master"
      - "SSHPIPERD_AUDITOR=typescript-logger"
      - "SSHPIPERD_BANNERTEXT=hellopiper"
    build: ../..
    links:
      - "host1:host1"
      - "host2:host2"
      - "mssql:mssql"
    volumes:
      - ./piper.sh:/piper.sh
      - workingdir:/var/sshpiper
      - ./wait.sh:/wait.sh
    command:
      - "/bin/sh"
      - "/piper.sh"
    depends_on:
      - mssql 
      - host1
      - host2
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU12-ubuntu
    environment:
      - "ACCEPT_EULA=y"
      - "SA_PASSWORD=yourStrong(!)Password"
      # - "MSSQL_PID=Developer"

    #tmpfs:
    #  - /var/opt/mssql/data


volumes:
  workingdir:
  localkey:
  host1ssh:
  names:
