// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: admin.proto

package libadmin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SshPiperAdmin_ServerInfo_FullMethodName    = "/libadmin.SshPiperAdmin/ServerInfo"
	SshPiperAdmin_ListSessions_FullMethodName  = "/libadmin.SshPiperAdmin/ListSessions"
	SshPiperAdmin_KillSession_FullMethodName   = "/libadmin.SshPiperAdmin/KillSession"
	SshPiperAdmin_StreamSession_FullMethodName = "/libadmin.SshPiperAdmin/StreamSession"
)

// SshPiperAdminClient is the client API for SshPiperAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SshPiperAdmin is the management API exposed by a sshpiperd instance.
// It is intended to be consumed by an out-of-band admin/aggregator service
// (for example sshpiperd-webadmin) to inspect and manage live SSH sessions.
type SshPiperAdminClient interface {
	// ServerInfo returns identifying information about this sshpiperd.
	ServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error)
	// ListSessions returns all currently active piped SSH sessions.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// KillSession closes the sshpiperd pipe identified by id, terminating
	// both the downstream and upstream SSH connections.
	KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*KillSessionResponse, error)
	// StreamSession streams asciicast v2 frames captured from the upstream
	// shell/exec channel of the given session in real time. The first frame
	// sent by the server is always a header frame describing the terminal,
	// followed by output ("o") and resize ("r") frames as they happen.
	StreamSession(ctx context.Context, in *StreamSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionFrame], error)
}

type sshPiperAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewSshPiperAdminClient(cc grpc.ClientConnInterface) SshPiperAdminClient {
	return &sshPiperAdminClient{cc}
}

func (c *sshPiperAdminClient) ServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, SshPiperAdmin_ServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperAdminClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SshPiperAdmin_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperAdminClient) KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*KillSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillSessionResponse)
	err := c.cc.Invoke(ctx, SshPiperAdmin_KillSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sshPiperAdminClient) StreamSession(ctx context.Context, in *StreamSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SshPiperAdmin_ServiceDesc.Streams[0], SshPiperAdmin_StreamSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSessionRequest, SessionFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SshPiperAdmin_StreamSessionClient = grpc.ServerStreamingClient[SessionFrame]

// SshPiperAdminServer is the server API for SshPiperAdmin service.
// All implementations must embed UnimplementedSshPiperAdminServer
// for forward compatibility.
//
// SshPiperAdmin is the management API exposed by a sshpiperd instance.
// It is intended to be consumed by an out-of-band admin/aggregator service
// (for example sshpiperd-webadmin) to inspect and manage live SSH sessions.
type SshPiperAdminServer interface {
	// ServerInfo returns identifying information about this sshpiperd.
	ServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error)
	// ListSessions returns all currently active piped SSH sessions.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// KillSession closes the sshpiperd pipe identified by id, terminating
	// both the downstream and upstream SSH connections.
	KillSession(context.Context, *KillSessionRequest) (*KillSessionResponse, error)
	// StreamSession streams asciicast v2 frames captured from the upstream
	// shell/exec channel of the given session in real time. The first frame
	// sent by the server is always a header frame describing the terminal,
	// followed by output ("o") and resize ("r") frames as they happen.
	StreamSession(*StreamSessionRequest, grpc.ServerStreamingServer[SessionFrame]) error
	mustEmbedUnimplementedSshPiperAdminServer()
}

// UnimplementedSshPiperAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSshPiperAdminServer struct{}

func (UnimplementedSshPiperAdminServer) ServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerInfo not implemented")
}
func (UnimplementedSshPiperAdminServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSshPiperAdminServer) KillSession(context.Context, *KillSessionRequest) (*KillSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillSession not implemented")
}
func (UnimplementedSshPiperAdminServer) StreamSession(*StreamSessionRequest, grpc.ServerStreamingServer[SessionFrame]) error {
	return status.Error(codes.Unimplemented, "method StreamSession not implemented")
}
func (UnimplementedSshPiperAdminServer) mustEmbedUnimplementedSshPiperAdminServer() {}
func (UnimplementedSshPiperAdminServer) testEmbeddedByValue()                       {}

// UnsafeSshPiperAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SshPiperAdminServer will
// result in compilation errors.
type UnsafeSshPiperAdminServer interface {
	mustEmbedUnimplementedSshPiperAdminServer()
}

func RegisterSshPiperAdminServer(s grpc.ServiceRegistrar, srv SshPiperAdminServer) {
	// If the following call panics, it indicates UnimplementedSshPiperAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SshPiperAdmin_ServiceDesc, srv)
}

func _SshPiperAdmin_ServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperAdminServer).ServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperAdmin_ServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperAdminServer).ServerInfo(ctx, req.(*ServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperAdmin_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperAdminServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperAdmin_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperAdminServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperAdmin_KillSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SshPiperAdminServer).KillSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SshPiperAdmin_KillSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SshPiperAdminServer).KillSession(ctx, req.(*KillSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SshPiperAdmin_StreamSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSessionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SshPiperAdminServer).StreamSession(m, &grpc.GenericServerStream[StreamSessionRequest, SessionFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SshPiperAdmin_StreamSessionServer = grpc.ServerStreamingServer[SessionFrame]

// SshPiperAdmin_ServiceDesc is the grpc.ServiceDesc for SshPiperAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SshPiperAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "libadmin.SshPiperAdmin",
	HandlerType: (*SshPiperAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerInfo",
			Handler:    _SshPiperAdmin_ServerInfo_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _SshPiperAdmin_ListSessions_Handler,
		},
		{
			MethodName: "KillSession",
			Handler:    _SshPiperAdmin_KillSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSession",
			Handler:       _SshPiperAdmin_StreamSession_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "admin.proto",
}
