// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: admin.proto

package libadmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

type ServerInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier for this sshpiperd instance. Defaults to the host
	// name plus listening address, but may be overridden via configuration.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable version string (matches `sshpiperd --version`).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Address the SSH listener is bound to.
	SshAddr string `protobuf:"bytes,3,opt,name=ssh_addr,json=sshAddr,proto3" json:"ssh_addr,omitempty"`
	// Wall-clock time the daemon started, as a unix timestamp in seconds.
	StartedAt     int64 `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfoResponse) GetSshAddr() string {
	if x != nil {
		return x.SshAddr
	}
	return ""
}

func (x *ServerInfoResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique session id (matches the `uniq_id` used elsewhere in sshpiperd).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Downstream (client) connection details.
	DownstreamUser string `protobuf:"bytes,2,opt,name=downstream_user,json=downstreamUser,proto3" json:"downstream_user,omitempty"`
	DownstreamAddr string `protobuf:"bytes,3,opt,name=downstream_addr,json=downstreamAddr,proto3" json:"downstream_addr,omitempty"`
	// Upstream (target server) connection details.
	UpstreamUser string `protobuf:"bytes,4,opt,name=upstream_user,json=upstreamUser,proto3" json:"upstream_user,omitempty"`
	UpstreamAddr string `protobuf:"bytes,5,opt,name=upstream_addr,json=upstreamAddr,proto3" json:"upstream_addr,omitempty"`
	// Wall-clock time the pipe was established, as a unix timestamp in seconds.
	StartedAt int64 `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// True if at least one shell/exec channel is currently being recorded
	// and can therefore be live-streamed via StreamSession.
	Streamable    bool `protobuf:"varint,7,opt,name=streamable,proto3" json:"streamable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetDownstreamUser() string {
	if x != nil {
		return x.DownstreamUser
	}
	return ""
}

func (x *Session) GetDownstreamAddr() string {
	if x != nil {
		return x.DownstreamAddr
	}
	return ""
}

func (x *Session) GetUpstreamUser() string {
	if x != nil {
		return x.UpstreamUser
	}
	return ""
}

func (x *Session) GetUpstreamAddr() string {
	if x != nil {
		return x.UpstreamAddr
	}
	return ""
}

func (x *Session) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Session) GetStreamable() bool {
	if x != nil {
		return x.Streamable
	}
	return false
}

type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *KillSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KillSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if a matching session was found and signalled to close.
	Killed        bool `protobuf:"varint,1,opt,name=killed,proto3" json:"killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionResponse) Reset() {
	*x = KillSessionResponse{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionResponse) ProtoMessage() {}

func (x *KillSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionResponse.ProtoReflect.Descriptor instead.
func (*KillSessionResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *KillSessionResponse) GetKilled() bool {
	if x != nil {
		return x.Killed
	}
	return false
}

type StreamSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// If true, the server will replay the asciicast captured so far before
	// switching to live streaming. If false, the client only receives new
	// frames from the moment the stream is opened (plus a synthetic header).
	Replay        bool `protobuf:"varint,2,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSessionRequest) Reset() {
	*x = StreamSessionRequest{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSessionRequest) ProtoMessage() {}

func (x *StreamSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSessionRequest.ProtoReflect.Descriptor instead.
func (*StreamSessionRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *StreamSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamSessionRequest) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

// SessionFrame mirrors the asciicast v2 file format:
// the first message is always a header; subsequent messages are events.
type SessionFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*SessionFrame_Header
	//	*SessionFrame_Event
	Frame         isSessionFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionFrame) Reset() {
	*x = SessionFrame{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFrame) ProtoMessage() {}

func (x *SessionFrame) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFrame.ProtoReflect.Descriptor instead.
func (*SessionFrame) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *SessionFrame) GetFrame() isSessionFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *SessionFrame) GetHeader() *AsciicastHeader {
	if x != nil {
		if x, ok := x.Frame.(*SessionFrame_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *SessionFrame) GetEvent() *AsciicastEvent {
	if x != nil {
		if x, ok := x.Frame.(*SessionFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isSessionFrame_Frame interface {
	isSessionFrame_Frame()
}

type SessionFrame_Header struct {
	Header *AsciicastHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type SessionFrame_Event struct {
	Event *AsciicastEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*SessionFrame_Header) isSessionFrame_Frame() {}

func (*SessionFrame_Event) isSessionFrame_Frame() {}

type AsciicastHeader struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Width     int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height    int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Env       map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional channel id this header refers to, allowing multiple
	// concurrent shells to be distinguished within a single session.
	ChannelId     uint32 `protobuf:"varint,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsciicastHeader) Reset() {
	*x = AsciicastHeader{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsciicastHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsciicastHeader) ProtoMessage() {}

func (x *AsciicastHeader) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsciicastHeader.ProtoReflect.Descriptor instead.
func (*AsciicastHeader) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AsciicastHeader) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AsciicastHeader) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AsciicastHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AsciicastHeader) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AsciicastHeader) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type AsciicastEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seconds since the corresponding header timestamp.
	Time float64 `protobuf:"fixed64,1,opt,name=time,proto3" json:"time,omitempty"`
	// Event kind, matching asciicast: "o" (output), "r" (resize), "i" (input).
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// For "o"/"i": raw bytes. For "r": "WIDTHxHEIGHT" string encoded as bytes.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ChannelId     uint32 `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsciicastEvent) Reset() {
	*x = AsciicastEvent{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsciicastEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsciicastEvent) ProtoMessage() {}

func (x *AsciicastEvent) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsciicastEvent.ProtoReflect.Descriptor instead.
func (*AsciicastEvent) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AsciicastEvent) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AsciicastEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AsciicastEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AsciicastEvent) GetChannelId() uint32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\blibadmin\"\x13\n" +
	"\x11ServerInfoRequest\"x\n" +
	"\x12ServerInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bssh_addr\x18\x03 \x01(\tR\asshAddr\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\"\x15\n" +
	"\x13ListSessionsRequest\"E\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.libadmin.SessionR\bsessions\"\xf4\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fdownstream_user\x18\x02 \x01(\tR\x0edownstreamUser\x12'\n" +
	"\x0fdownstream_addr\x18\x03 \x01(\tR\x0edownstreamAddr\x12#\n" +
	"\rupstream_user\x18\x04 \x01(\tR\fupstreamUser\x12#\n" +
	"\rupstream_addr\x18\x05 \x01(\tR\fupstreamAddr\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x1e\n" +
	"\n" +
	"streamable\x18\a \x01(\bR\n" +
	"streamable\"$\n" +
	"\x12KillSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x13KillSessionResponse\x12\x16\n" +
	"\x06killed\x18\x01 \x01(\bR\x06killed\">\n" +
	"\x14StreamSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06replay\x18\x02 \x01(\bR\x06replay\"~\n" +
	"\fSessionFrame\x123\n" +
	"\x06header\x18\x01 \x01(\v2\x19.libadmin.AsciicastHeaderH\x00R\x06header\x120\n" +
	"\x05event\x18\x02 \x01(\v2\x18.libadmin.AsciicastEventH\x00R\x05eventB\a\n" +
	"\x05frame\"\xea\x01\n" +
	"\x0fAsciicastHeader\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x124\n" +
	"\x03env\x18\x04 \x03(\v2\".libadmin.AsciicastHeader.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\rR\tchannelId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x0eAsciicastEvent\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x01R\x04time\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\rR\tchannelId2\xc6\x02\n" +
	"\rSshPiperAdmin\x12I\n" +
	"\n" +
	"ServerInfo\x12\x1b.libadmin.ServerInfoRequest\x1a\x1c.libadmin.ServerInfoResponse\"\x00\x12O\n" +
	"\fListSessions\x12\x1d.libadmin.ListSessionsRequest\x1a\x1e.libadmin.ListSessionsResponse\"\x00\x12L\n" +
	"\vKillSession\x12\x1c.libadmin.KillSessionRequest\x1a\x1d.libadmin.KillSessionResponse\"\x00\x12K\n" +
	"\rStreamSession\x12\x1e.libadmin.StreamSessionRequest\x1a\x16.libadmin.SessionFrame\"\x000\x01B$Z\"github.com/tg123/sshpiper/libadminb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_admin_proto_goTypes = []any{
	(*ServerInfoRequest)(nil),    // 0: libadmin.ServerInfoRequest
	(*ServerInfoResponse)(nil),   // 1: libadmin.ServerInfoResponse
	(*ListSessionsRequest)(nil),  // 2: libadmin.ListSessionsRequest
	(*ListSessionsResponse)(nil), // 3: libadmin.ListSessionsResponse
	(*Session)(nil),              // 4: libadmin.Session
	(*KillSessionRequest)(nil),   // 5: libadmin.KillSessionRequest
	(*KillSessionResponse)(nil),  // 6: libadmin.KillSessionResponse
	(*StreamSessionRequest)(nil), // 7: libadmin.StreamSessionRequest
	(*SessionFrame)(nil),         // 8: libadmin.SessionFrame
	(*AsciicastHeader)(nil),      // 9: libadmin.AsciicastHeader
	(*AsciicastEvent)(nil),       // 10: libadmin.AsciicastEvent
	nil,                          // 11: libadmin.AsciicastHeader.EnvEntry
}
var file_admin_proto_depIdxs = []int32{
	4,  // 0: libadmin.ListSessionsResponse.sessions:type_name -> libadmin.Session
	9,  // 1: libadmin.SessionFrame.header:type_name -> libadmin.AsciicastHeader
	10, // 2: libadmin.SessionFrame.event:type_name -> libadmin.AsciicastEvent
	11, // 3: libadmin.AsciicastHeader.env:type_name -> libadmin.AsciicastHeader.EnvEntry
	0,  // 4: libadmin.SshPiperAdmin.ServerInfo:input_type -> libadmin.ServerInfoRequest
	2,  // 5: libadmin.SshPiperAdmin.ListSessions:input_type -> libadmin.ListSessionsRequest
	5,  // 6: libadmin.SshPiperAdmin.KillSession:input_type -> libadmin.KillSessionRequest
	7,  // 7: libadmin.SshPiperAdmin.StreamSession:input_type -> libadmin.StreamSessionRequest
	1,  // 8: libadmin.SshPiperAdmin.ServerInfo:output_type -> libadmin.ServerInfoResponse
	3,  // 9: libadmin.SshPiperAdmin.ListSessions:output_type -> libadmin.ListSessionsResponse
	6,  // 10: libadmin.SshPiperAdmin.KillSession:output_type -> libadmin.KillSessionResponse
	8,  // 11: libadmin.SshPiperAdmin.StreamSession:output_type -> libadmin.SessionFrame
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_admin_proto_msgTypes[8].OneofWrappers = []any{
		(*SessionFrame_Header)(nil),
		(*SessionFrame_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
