// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: connovergrpc.proto

package connovergrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnMessage carries a net.Conn tunneled over a bidirectional gRPC stream.
// The first message in a stream carries an opaque, application-defined request
// describing the connection to create; all subsequent messages in both
// directions carry the tunneled connection bytes. connovergrpc itself does not
// interpret the request bytes - the application owns their format.
type ConnMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ConnMessage_Request
	//	*ConnMessage_Data
	Message       isConnMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnMessage) Reset() {
	*x = ConnMessage{}
	mi := &file_connovergrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnMessage) ProtoMessage() {}

func (x *ConnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_connovergrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnMessage.ProtoReflect.Descriptor instead.
func (*ConnMessage) Descriptor() ([]byte, []int) {
	return file_connovergrpc_proto_rawDescGZIP(), []int{0}
}

func (x *ConnMessage) GetMessage() isConnMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ConnMessage) GetRequest() []byte {
	if x != nil {
		if x, ok := x.Message.(*ConnMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ConnMessage) GetData() []byte {
	if x != nil {
		if x, ok := x.Message.(*ConnMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isConnMessage_Message interface {
	isConnMessage_Message()
}

type ConnMessage_Request struct {
	Request []byte `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type ConnMessage_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ConnMessage_Request) isConnMessage_Message() {}

func (*ConnMessage_Data) isConnMessage_Message() {}

var File_connovergrpc_proto protoreflect.FileDescriptor

const file_connovergrpc_proto_rawDesc = "" +
	"\n" +
	"\x12connovergrpc.proto\x12\fconnovergrpc\"J\n" +
	"\vConnMessage\x12\x1a\n" +
	"\arequest\x18\x01 \x01(\fH\x00R\arequest\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\amessage2X\n" +
	"\fConnOverGrpc\x12H\n" +
	"\n" +
	"CreateConn\x12\x19.connovergrpc.ConnMessage\x1a\x19.connovergrpc.ConnMessage\"\x00(\x010\x01B2Z0github.com/tg123/sshpiper/libplugin/connovergrpcb\x06proto3"

var (
	file_connovergrpc_proto_rawDescOnce sync.Once
	file_connovergrpc_proto_rawDescData []byte
)

func file_connovergrpc_proto_rawDescGZIP() []byte {
	file_connovergrpc_proto_rawDescOnce.Do(func() {
		file_connovergrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connovergrpc_proto_rawDesc), len(file_connovergrpc_proto_rawDesc)))
	})
	return file_connovergrpc_proto_rawDescData
}

var file_connovergrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connovergrpc_proto_goTypes = []any{
	(*ConnMessage)(nil), // 0: connovergrpc.ConnMessage
}
var file_connovergrpc_proto_depIdxs = []int32{
	0, // 0: connovergrpc.ConnOverGrpc.CreateConn:input_type -> connovergrpc.ConnMessage
	0, // 1: connovergrpc.ConnOverGrpc.CreateConn:output_type -> connovergrpc.ConnMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_connovergrpc_proto_init() }
func file_connovergrpc_proto_init() {
	if File_connovergrpc_proto != nil {
		return
	}
	file_connovergrpc_proto_msgTypes[0].OneofWrappers = []any{
		(*ConnMessage_Request)(nil),
		(*ConnMessage_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connovergrpc_proto_rawDesc), len(file_connovergrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connovergrpc_proto_goTypes,
		DependencyIndexes: file_connovergrpc_proto_depIdxs,
		MessageInfos:      file_connovergrpc_proto_msgTypes,
	}.Build()
	File_connovergrpc_proto = out.File
	file_connovergrpc_proto_goTypes = nil
	file_connovergrpc_proto_depIdxs = nil
}
