// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: connovergrpc.proto

package connovergrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnOverGrpc_CreateConn_FullMethodName = "/connovergrpc.ConnOverGrpc/CreateConn"
)

// ConnOverGrpcClient is the client API for ConnOverGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnOverGrpc tunnels a net.Conn over a bidirectional gRPC stream. It is a
// self-contained, application-agnostic service: the first message of a
// CreateConn stream carries the opaque request and every following message in
// either direction carries the connection bytes. Any program can import this
// package, register a ConnOverGrpcServer, and use the generated client to
// obtain a net.Conn via the helpers in this package.
type ConnOverGrpcClient interface {
	CreateConn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnMessage, ConnMessage], error)
}

type connOverGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewConnOverGrpcClient(cc grpc.ClientConnInterface) ConnOverGrpcClient {
	return &connOverGrpcClient{cc}
}

func (c *connOverGrpcClient) CreateConn(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnMessage, ConnMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnOverGrpc_ServiceDesc.Streams[0], ConnOverGrpc_CreateConn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnMessage, ConnMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnOverGrpc_CreateConnClient = grpc.BidiStreamingClient[ConnMessage, ConnMessage]

// ConnOverGrpcServer is the server API for ConnOverGrpc service.
// All implementations must embed UnimplementedConnOverGrpcServer
// for forward compatibility.
//
// ConnOverGrpc tunnels a net.Conn over a bidirectional gRPC stream. It is a
// self-contained, application-agnostic service: the first message of a
// CreateConn stream carries the opaque request and every following message in
// either direction carries the connection bytes. Any program can import this
// package, register a ConnOverGrpcServer, and use the generated client to
// obtain a net.Conn via the helpers in this package.
type ConnOverGrpcServer interface {
	CreateConn(grpc.BidiStreamingServer[ConnMessage, ConnMessage]) error
	mustEmbedUnimplementedConnOverGrpcServer()
}

// UnimplementedConnOverGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnOverGrpcServer struct{}

func (UnimplementedConnOverGrpcServer) CreateConn(grpc.BidiStreamingServer[ConnMessage, ConnMessage]) error {
	return status.Error(codes.Unimplemented, "method CreateConn not implemented")
}
func (UnimplementedConnOverGrpcServer) mustEmbedUnimplementedConnOverGrpcServer() {}
func (UnimplementedConnOverGrpcServer) testEmbeddedByValue()                      {}

// UnsafeConnOverGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnOverGrpcServer will
// result in compilation errors.
type UnsafeConnOverGrpcServer interface {
	mustEmbedUnimplementedConnOverGrpcServer()
}

func RegisterConnOverGrpcServer(s grpc.ServiceRegistrar, srv ConnOverGrpcServer) {
	// If the following call panics, it indicates UnimplementedConnOverGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnOverGrpc_ServiceDesc, srv)
}

func _ConnOverGrpc_CreateConn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnOverGrpcServer).CreateConn(&grpc.GenericServerStream[ConnMessage, ConnMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnOverGrpc_CreateConnServer = grpc.BidiStreamingServer[ConnMessage, ConnMessage]

// ConnOverGrpc_ServiceDesc is the grpc.ServiceDesc for ConnOverGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnOverGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connovergrpc.ConnOverGrpc",
	HandlerType: (*ConnOverGrpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateConn",
			Handler:       _ConnOverGrpc_CreateConn_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connovergrpc.proto",
}
