// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: connovergrpc.proto

package connovergrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Packet is the frame exchanged on a CreateConn stream. The first packet from
// the client must be a DialRequest; all later packets in both directions
// carry connection bytes.
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_DialRequest
	//	*Packet_Data
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_connovergrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_connovergrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_connovergrpc_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetDialRequest() *DialRequest {
	if x != nil {
		if x, ok := x.Payload.(*Packet_DialRequest); ok {
			return x.DialRequest
		}
	}
	return nil
}

func (x *Packet) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_DialRequest struct {
	DialRequest *DialRequest `protobuf:"bytes,1,opt,name=dialRequest,proto3,oneof"`
}

type Packet_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*Packet_DialRequest) isPacket_Payload() {}

func (*Packet_Data) isPacket_Payload() {}

// DialRequest selects the upstream to dial. Fields are interpreted by the
// server-side CreateConnFunc; connovergrpc does not look at them. New fields
// can be added in a backwards-compatible way.
type DialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// application-defined upstream URI
	Uri           string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	mi := &file_connovergrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connovergrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_connovergrpc_proto_rawDescGZIP(), []int{1}
}

func (x *DialRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

var File_connovergrpc_proto protoreflect.FileDescriptor

const file_connovergrpc_proto_rawDesc = "" +
	"\n" +
	"\x12connovergrpc.proto\x12\fconnovergrpc\"h\n" +
	"\x06Packet\x12=\n" +
	"\vdialRequest\x18\x01 \x01(\v2\x19.connovergrpc.DialRequestH\x00R\vdialRequest\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x1f\n" +
	"\vDialRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri2N\n" +
	"\fConnOverGrpc\x12>\n" +
	"\n" +
	"CreateConn\x12\x14.connovergrpc.Packet\x1a\x14.connovergrpc.Packet\"\x00(\x010\x01B2Z0github.com/tg123/sshpiper/libplugin/connovergrpcb\x06proto3"

var (
	file_connovergrpc_proto_rawDescOnce sync.Once
	file_connovergrpc_proto_rawDescData []byte
)

func file_connovergrpc_proto_rawDescGZIP() []byte {
	file_connovergrpc_proto_rawDescOnce.Do(func() {
		file_connovergrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connovergrpc_proto_rawDesc), len(file_connovergrpc_proto_rawDesc)))
	})
	return file_connovergrpc_proto_rawDescData
}

var file_connovergrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_connovergrpc_proto_goTypes = []any{
	(*Packet)(nil),      // 0: connovergrpc.Packet
	(*DialRequest)(nil), // 1: connovergrpc.DialRequest
}
var file_connovergrpc_proto_depIdxs = []int32{
	1, // 0: connovergrpc.Packet.dialRequest:type_name -> connovergrpc.DialRequest
	0, // 1: connovergrpc.ConnOverGrpc.CreateConn:input_type -> connovergrpc.Packet
	0, // 2: connovergrpc.ConnOverGrpc.CreateConn:output_type -> connovergrpc.Packet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connovergrpc_proto_init() }
func file_connovergrpc_proto_init() {
	if File_connovergrpc_proto != nil {
		return
	}
	file_connovergrpc_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_DialRequest)(nil),
		(*Packet_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connovergrpc_proto_rawDesc), len(file_connovergrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connovergrpc_proto_goTypes,
		DependencyIndexes: file_connovergrpc_proto_depIdxs,
		MessageInfos:      file_connovergrpc_proto_msgTypes,
	}.Build()
	File_connovergrpc_proto = out.File
	file_connovergrpc_proto_goTypes = nil
	file_connovergrpc_proto_depIdxs = nil
}
