name: E2E

permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    
jobs:

  E2E:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Expose GitHub Actions cache to buildx
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Kind Warmup
      run: kind create cluster -n sshpipertest
      
    - name: Run E2E
      run: docker compose up --build --abort-on-container-exit --exit-code-from testrunner
      working-directory: e2e
      env:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
        E2E_TESTRUNNER_CACHE_FROM: type=gha,scope=e2e-testrunner
        E2E_TESTRUNNER_CACHE_TO: type=gha,scope=e2e-testrunner,mode=max
        E2E_PIPER_CACHE_FROM: type=gha,scope=e2e-piper
        E2E_PIPER_CACHE_TO: type=gha,scope=e2e-piper,mode=max
